name: lighthouse_buffet
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.16
  get_it: ^8.0.2
  internet_connection_checker: ^1.0.0+1
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true



  assets:
    - assets/
    - assets/gif/qr scanner.mp4
    - assets/svg/
    - assets/gif/
